export const sessions = [
  {
    id: "s001",
    name: "Cortical Array Session 07",
    lifecycle: "Active",
    health: "Healthy",
    experiment: "Motor Learning Study",
    startTime: "2026-06-19T06:14:00",
    duration: "2h 34m",
    deviceCount: 2,
    streamCount: 2,
    sinkCount: 4,
    watchdog: "Current",
    isOwner: true,
  },
  {
    id: "s002",
    name: "Striatal LFP Recording",
    lifecycle: "Active",
    health: "Needs action",
    experiment: "Sleep Stage Analysis",
    startTime: "2026-06-19T04:55:00",
    duration: "3h 53m",
    deviceCount: 1,
    streamCount: 1,
    sinkCount: 2,
    watchdog: "Delayed",
    attentionReason: "Sink write verification failed after recovery",
    attentionSince: "08:42",
    isOwner: true,
  },
  {
    id: "s003",
    name: "Hippocampal Theta Session",
    lifecycle: "Scheduled",
    health: "Unknown",
    experiment: "Motor Learning Study",
    scheduledTime: "2026-06-20T08:00:00",
    deviceCount: 1,
    streamCount: 1,
    sinkCount: 2,
    watchdog: "Stopped",
    isOwner: true,
  },
  {
    id: "s004",
    name: "Visual Cortex Mapping",
    lifecycle: "Draft",
    health: "Unknown",
    deviceCount: 0,
    streamCount: 0,
    sinkCount: 0,
    watchdog: "Stopped",
    isOwner: true,
  },
  {
    id: "s005",
    name: "Auditory Evoked Potentials",
    lifecycle: "Completed",
    health: "Healthy",
    experiment: "Sleep Stage Analysis",
    startTime: "2026-06-18T10:00:00",
    duration: "6h 12m",
    deviceCount: 2,
    streamCount: 2,
    sinkCount: 3,
    watchdog: "Stopped",
    isOwner: true,
  },
  {
    id: "s006",
    name: "Prefrontal Sync - Archive",
    lifecycle: "Completed",
    health: "Healthy",
    experiment: "Motor Learning Study",
    startTime: "2026-06-15T09:00:00",
    duration: "4h 00m",
    deviceCount: 1,
    streamCount: 1,
    sinkCount: 2,
    watchdog: "Stopped",
    isOwner: true,
    archived: true,
  },
];

export const incidents = [
  {
    id: "i001",
    sessionId: "s002",
    sessionName: "Striatal LFP Recording",
    stream: "M16-003",
    time: "08:42",
    reason: "Heartbeat timeout - device did not respond within 15 s",
    outcome: "Needs action",
    resolved: false,
  },
  {
    id: "i002",
    sessionId: "s001",
    sessionName: "Cortical Array Session 07",
    stream: "M32-007",
    time: "07:11",
    reason: "Sink write stall - NFS mount latency spike",
    outcome: "Recovered",
    resolved: true,
  },
  {
    id: "i003",
    sessionId: "s005",
    sessionName: "Auditory Evoked Potentials",
    stream: "M16-002",
    time: "Jun 18 14:23",
    reason: "Device reconnect after cable disturbance",
    outcome: "Recovered",
    resolved: true,
  },
];

export const deviceFlows = [
  {
    id: "flow-3c8d",
    sessionId: "s001",
    device: "M32-007",
    type: "Morelia-32ch",
    hardwareId: "M32-007-HW",
    health: "Healthy",
    rate: "32.4 kS/s",
    lastData: "08:48:31",
    watchdog: "Current",
    sinks: [
      { name: "Raw LFP", path: "/data/cortical/session07_M32007_rawlfp.bin", health: "Healthy" },
      { name: "Spike Sort", path: "/data/cortical/session07_M32007_spikesort.bin", health: "Healthy" },
    ],
  },
  {
    id: "flow-1b2c",
    sessionId: "s001",
    device: "M16-004",
    type: "Morelia-16ch",
    hardwareId: "M16-004-HW",
    health: "Healthy",
    rate: "16.1 kS/s",
    lastData: "08:48:31",
    watchdog: "Current",
    sinks: [
      { name: "Analog In", path: "/data/cortical/session07_M16004_analogin.bin", health: "Healthy" },
      { name: "Digital Events", path: "/data/cortical/session07_M16004_events.bin", health: "Healthy" },
    ],
  },
  {
    id: "flow-9f2a",
    sessionId: "s002",
    device: "M16-003",
    type: "Morelia-16ch",
    hardwareId: "M16-003-HW",
    health: "Unhealthy",
    rate: "0 kS/s",
    lastData: "08:42:11",
    watchdog: "Delayed",
    sinks: [
      { name: "Raw LFP", path: "/data/striatal/lfp_recording_raw.bin", health: "Unhealthy" },
      { name: "Sleep Staging", path: "/data/striatal/lfp_recording_staging.bin", health: "Unknown" },
    ],
  },
];

export const experiments = [
  { name: "Motor Learning Study", description: "Cortical and hippocampal learning sessions", sessions: 4, active: 1, attention: 0 },
  { name: "Sleep Stage Analysis", description: "Long-form LFP acquisition and sleep staging", sessions: 2, active: 1, attention: 1 },
];

export const devices = [
  {
    name: "M32-007",
    type: "pod8206hr",
    hardwareId: "M32-007-HW",
    port: "COM7",
    availability: "available",
    status: "free",
    configSource: "Standard M32 Cortical",
    owningSession: "-",
    lastSeen: "08:49:12",
  },
  {
    name: "M16-003",
    type: "pod8206hr",
    hardwareId: "M16-003-HW",
    port: "COM4",
    availability: "available",
    status: "claimed",
    configSource: "Custom (was Standard M16 LFP)",
    owningSession: "Striatal LFP Recording",
    lastSeen: "08:42:11",
    portMismatch: true,
  },
  {
    name: "M16-004",
    type: "pod8206hr",
    hardwareId: "M16-004-HW",
    port: "COM5",
    availability: "available",
    status: "free",
    configSource: "Standard M16 LFP",
    owningSession: "-",
    lastSeen: "08:49:09",
    templateDrift: true,
  },
  {
    name: "M64-009",
    type: "pod8206hr",
    hardwareId: "M64-009-HW",
    port: "COM9",
    availability: "not_found",
    status: "unconfigured",
    configSource: "-",
    owningSession: "-",
    lastSeen: "Jun 18, 16:22",
  },
];

export const deviceTemplates = [
  { name: "Standard M32 Cortical", type: "pod8206hr", schemaVersion: "2026.1", contentHash: "9f1a2c7d", sessionsUsing: 8, created: "Jun 19" },
  { name: "Standard M16 LFP", type: "pod8206hr", schemaVersion: "2026.1", contentHash: "4b0e17ac", sessionsUsing: 12, created: "Jun 18" },
  { name: "Bench Test Template", type: "pod8206hr", schemaVersion: "2026.1", contentHash: "c83d9e10", sessionsUsing: 2, created: "Jun 16" },
];

export const sessionTemplates = [
  { name: "Cortical Dual Stream", streams: 2, sinks: 4, policy: "Recommend", sourceSession: "Cortical Array Session 07", lastExported: "Jun 19" },
  { name: "Striatal LFP Baseline", streams: 1, sinks: 2, policy: "Recommend", sourceSession: "Striatal LFP Recording", lastExported: "Jun 18" },
];
