{
 "title": "ttyUSB0 Dashboard",
 "description": "Influx Dashboard for 8206HR",
 "time": { "from": "now-10s", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Channel View TTL1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"influx_dump\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"default-measurement\" and\r\n      r._field == \"value\" and\r\n      r.channel == \"TTL1\" and\n    r.name == \"/dev/ttyUSB0\"\n  )   \r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Channel View TTL2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"influx_dump\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"default-measurement\" and\r\n      r._field == \"value\" and\r\n      r.channel == \"TTL2\" and\n    r.name == \"/dev/ttyUSB0\"\n  )   \r\n  |> yield(name: \"mean\")",
     "rawSql": "from(bucket: \"influx_dump\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"experiment1\" and\r\n      r._field == \"value\" and\r\n      r.channel == \"TTL2\" and\r\n      r._value < 2\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Channel View TTL3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"influx_dump\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"default-measurement\" and\r\n      r._field == \"value\" and\r\n      r.channel == \"TTL3\" and\n    r.name == \"/dev/ttyUSB0\"\n  )   \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Channel View TTL4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"influx_dump\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"default-measurement\" and\r\n      r._field == \"value\" and\r\n      r.channel == \"TTL4\" and\n    r.name == \"/dev/ttyUSB0\"\n  )   \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Channel View CH0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"influx_dump\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"default-measurement\" and\r\n      r._field == \"value\" and\r\n      r.channel == \"CH0\" and\n    r.name == \"/dev/ttyUSB0\"\n  )   \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Channel View CH1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"influx_dump\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"default-measurement\" and\r\n      r._field == \"value\" and\r\n      r.channel == \"CH1\" and\n    r.name == \"/dev/ttyUSB0\"\n  )   \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Channel View CH2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"influx_dump\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"default-measurement\" and\r\n      r._field == \"value\" and\r\n      r.channel == \"CH2\" and\n    r.name == \"/dev/ttyUSB0\"\n  )   \r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}