{
 "title": "QuestDB Dashboard",
 "time": { "from": "now-10s", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Channel View TTL1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT value, timestamp FROM default_measurement WHERE channel='TTL1'"
    }
   ]
  },
  {
   "title": "Channel View TTL2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT value, timestamp FROM default_measurement WHERE channel='TTL2'"
    }
   ]
  },
  {
   "title": "Channel View TTL3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT value, timestamp FROM default_measurement WHERE channel='TTL3'"
    }
   ]
  },
  {
   "title": "Channel View TTL4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT value, timestamp FROM default_measurement WHERE channel='TTL4'"
    }
   ]
  },
  {
   "title": "Channel View CH0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT value, timestamp FROM default_measurement WHERE channel='CH0'"
    }
   ]
  },
  {
   "title": "Channel View CH1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT value, timestamp FROM default_measurement WHERE channel='CH1'"
    }
   ]
  },
  {
   "title": "Channel View CH2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT value, timestamp FROM default_measurement WHERE channel='CH2'"
    }
   ]
  }
 ]
}