title = "Pod8274D Device Configuration File"
filename = "8274D "

[channel_names]
channel_1 = "EEG1"
channel_2 = "EEG2"
channel_3 = "EEG3"

[information]
sample_rate = "400"
preamp_gain = "100"

[channel_settings]
eeg1 = "1"
eeg2 = "2"
emg = "3"
notch_enabled = "false"
notch_value = "4"

[ttl_controls.ttl1]
event_comment = "TTL 1"

[ttl_controls.ttl2]
event_comment = "TTL 2"

[ttl_controls.ttl3]
event_comment = "TTL 3"

[ttl_controls.ttl4]
event_comment = "TTL 4"
