# example TOML file for configuration from a UI

title = "Config TOML"

[Pod8206HR]

# number of devices being created
num_devices = 1

# specify ports on devices
ports = ["ttyUSB0"]

# specify preamp gain for devices
preamp = [10]

#[Pod8401HR]
#
## number of devices being created
#num_devices = 1
#
#class = "Pod8401HR"
#
## specify ports on devices
#ports = ["ttyUSB0"]
#
## specify preamp gain for devices
#preamp = [10]

[EDFSink]

num_sinks = 0

# files to create/dump into
file = ["dump_1.edf"]

# pods to use for various sinks (each is 1-1 mapping)
pods = ["pod_1"]
