name: documentation

on:
  push:
    branches:
      - integration

jobs:
  build-publish-docs:
    name: Build documentation.
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ammaraskar/sphinx-action@master
      - uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/integration'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
